{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    nomacs
    piper
    prismlauncher
    genymotion
    pciutils
    steam-run
    steam
    dmidecode
    lutris
    heroic
    wineWowPackages.waylandFull
    vesktop
    element-desktop
    telegram-desktop
    youtube-music
    cider
    transmission-gtk
    vivaldi
    samba
    unzip
    unrar
    unar
    mangohud
    nvme-cli
    smartmontools
    imagemagick
    fd
    transmission-remote-gtk
    ffmpegthumbnailer
    mediainfo
    weston
    cabextract
    appimage-run
    screen
    killall
    libimobiledevice
    ifuse
    # cemu
    dolphin-emu
    efibootmgr
    gimp
    pavucontrol
    btrfs-progs
    progress
    parted
    glxinfo
    gamescope
    nix-prefetch-github
    nix-prefetch-git
    cava
    bc
    ripgrep
    uget
    aria2
    ventoy
    e2fsprogs
    xarchiver
    p7zip
    breeze-icons
    gnome.nautilus
    openjdk
    gradience
    iwgtk
    distrobox
    gpu-screen-recorder
    gpu-screen-recorder-gtk
    scx
    gex
    inputs.nixpkgs-yuzu.legacyPackages.${pkgs.system}.citra
    remmina
    evince
  ];
  # services.flatpak.packages = [
  #   "org.telegram.desktop"
  # ];
}
