name: Flake check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          send-statistics: false
      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          diagnostic-endpoint: ""
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty
      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - name: Enter devshell
        run: nix develop
      - name: Check nix formatting
        run: git ls-files '*.nix' | xargs nix run nixpkgs#nixfmt-rfc-style -- --check ./
      - name: Scan .nix files for dead code
        run: git ls-files '*.nix' | nix run nixpkgs#deadnix
      - name: Check for lints and suggestions
        run: nix run nixpkgs#statix -- check
